wix/haste

packages/haste-core/test/haste.spec.js
The `hard-error-task` was flaky on [that ci run](https://travis-ci.org/wix/haste/builds/289408492#L541). 
__edit:__ which later restarted that build so now you can't really see the failure 😓...
I reckon that the `toContainEqual` method is not suitable when the console.log and the error output are in the same place.
I changed it to only want to test the output of the first call.
=> fix flaky test

packages/haste-core/src/haste.js, packages/haste-core/src/runner.js, packages/haste-core/src/task.js, packages/haste-core/src/utils.js, packages/haste-core/test/haste.spec.js
* task can now add metadata object, and later on use it in plugins.
```js
// on preset
const webpackProduction = {
task: 'webpack',
metadata: {
title: 'webpack-production',
},
options: {
configPath: paths.config.webpack.production
}
};
run(webpackProduction);
```
```js
// on plugin
apply(runner) {
runner.plugin('start-run', (runPhase) => {
console.log(runPhase.tasks[0].metadata.title) // webpack-production
})
}
```
* A small refactor to the testPlugin
* The test plugin can now emit `start-run` event to a `runPhase` stub, so we can make assertions on it.
* The test plugin is initialized before each test (less repetition on the constructor with the stubs)
* Simplify stdout mock usage, change it from a mock to a string which you can use `.toMatch` function in order to match output. It will …
=> task can now add a metadata object, which plugins can use later on

packages/haste-plugin-loader/src/utils.js, packages/haste-plugin-logger/src/index.js, packages/haste-plugin-logger/src/utils.js
* Aggregate start and end logs in logger to runs instead of tasks.
* Change `read` + `write` to `copy`.
* Accept `title` metadata when exist.
* update loader with same changes.
__NOTE:__ Right now we have code duplications between plugins about that stuff, we should probably export those functions to an external repository.
=> improve logging to work with runPhases and titles instead of task names

CHANGELOG.md, packages/haste-cli/bin/haste.js, packages/haste-core/src/haste.js, packages/haste-core/src/runner.js, packages/haste-core/test/haste.spec.js
when configured to be persistent and finished the initial run
=> runner now has an 'idle' state 

packages/haste-task-eslint/package.json
We're considering to move all (or most) tasks to use `peerDependencies` for their 3rd parties. This will allow presets to decide on the versions of 3rd party libraries.
This change only affects eslint but other tasks may follow with a similar change.
=> haste-task-eslint: move eslint to be a peer dependency

packages/haste-plugin-logger/src/index.js
This is a quick solution for the warning message when using more than 10 different tasks.
=> set max listeners on stdout and stderr to 100 for cases with more than 10 workers (the default)

package.json
Jest started to run very slowly lately, and some tests got to their timeout limit because of other tests that were written. jest tries to run the tests in parallel but on CI it only has 2 cores.
(Travis has only 2 cores on the free oss plan).
http://facebook.github.io/jest/docs/en/troubleshooting.html#tests-are-extremely-slow-on-docker-and-or-continuous-integration-ci-server
So let's configure jest to use only 2 workers on CI, stop the flakiness in our tests and make them run faster.
=> limit jest max workers to 2

packages/haste-task-read/src/index.js, packages/haste-task-read/test/index.spec.js
This fixes a problem introduced in #132: `filename` prop should be relative to `cwd`, instead it's now absolute.
This PR fixes that.
=> haste-task-read: fix 'filename' prop name always being absolute instead of being relative

packages/haste-task-protractor/package.json, packages/haste-task-protractor/src/index.js, packages/haste-task-protractor/test/index.spec.js
* Change the `webdriverManagerArgs<Array>` option to be `webdriverManagerOptions<Object>`
* Fix the merge between the passed options with the default options.
* Refactor tests
=> Haste task protractor fixes

packages/haste-task-copy/README.md, packages/haste-task-copy/src/index.js, packages/haste-task-copy/test/index.spec.js
`haste-task-copy` will now use the `cwd` of the file from the read task instead of its own `cwd` option in order to figure out the absolute path of a file.
https://github.com/wix/haste/blob/master/packages/haste-task-read/README.md#haste-task-read
=> haste-task-copy: (fix) use the cwd of the file instead of the cwd option to figure out the absolute path

packages/haste-task-tslint/src/index.js, packages/haste-task-tslint/test/index.spec.js
This PR corrects the way we use tslint API.
- Nothing is async here.
- `getResults()` aggregates all results, no need to call it every time we lint file. Moreover - it might emit duplicated errors this way (with a combination of `map`).
- `output` property is already formatted, `findFormatter` is redundant.
Btw, I'd exclude functions in `no-use-before-define` rule. I think it's better to first show the module's api itself (which is `module.exports` here) and not inner implementation (= `runLinter`), which is not necessarily interesting / harden code reading (you have to start from the EOF).
=> haste-task-tslint: correct tslint api usage

packages/haste-core/src/worker-bin.js
If we don't handle `uncaughtException` in the worker, a task could be hanged and the main process wouldn't know whether to resolve or reject.
=> haste-core: handle uncaughtException in worker

packages/haste-core/package.json, packages/haste-core/src/create-runner.js, packages/haste-core/src/runner.js, packages/haste-core/test/logger.spec.js, packages/haste-test-utils-core/src/index.js
Every plugin can write to the stdout, but there is a big mess when more than 1 does it.
In order to make sure that there is only one, let's create a `logger` entity. It will be a plugin like any other, with the same capabilities, but the only difference is that it will be allowed (by convention) to write things to the console.
We understand that haste does not work properly without a default logger.
It will be easier to start with haste when there is no need to bring a logger. (less configuration required)
**In this PR:**
1. An option to add a logger at the time of the runner creation.
2. A default logger if there is no logger supplied.
3. Tests for the functionality above.
4. The `test-utils` shall now use the logger in order to override the default logger (which create a mess in the …
=> Add a default Logger and a way to change it

packages/haste-service-fs/src/read.js, packages/haste-service-fs/test/read.spec.js, packages/haste-task-copy/src/index.js, packages/haste-task-copy/test/index.spec.js
Let's say that I want to copy all files from `src` directory into `dest` directory.
Today without supplying `source` you'll get the following:
```bash
├── root-directory
├── src
│    └── file.js
└── dist
└── src
└── file.js
```
But the wanted result would be:
```bash
├── root-directory
├── src
│    └── file.js
└─ dist
└── file.js
```
by choosing a `source` directory and a `target` directory both should be relative to the `root-directory`.
You can get this result.
=> accept source option to copy files from a source directory

packages/haste-core/src/task.js, packages/haste-core/test/haste.spec.js, packages/haste-test-utils-core/src/index.js, packages/haste-worker-farm/src/pool.js
Enable to pass `runnerOptions` as a second argument along with the `taskOptions` for every `task.api` call.
Recieve this argument from the plugins and be able to later use it to configure the runner in various ways, like calling the spawned process with different options, to possibly change the `env` or add `--debug-brk`.
```js
const taskOptions = {};
const runnerOptions = { title: 'my-awesome-task' };
await task(taskOptions, runnerOptions);
```
**NOTE:** Also exported the runner from `haste-test-utils-core` to be able and make assertions on hooks.
=> Runner options

packages/haste-core/src/execution.js, packages/haste-core/src/runner.js, packages/haste-core/src/task.js
This PR will solve an issue of creating duplicate listeners instead of taking care the worker's termination from one main place.
=> haste-core: kill all workers from one place when the main process exits

packages/haste-worker-farm/src/worker-bin.js
Will be handled like any other worker error.
Fixed a bug that `uncaughtException`s was hidden from the users.
=> haste-worker-farm: uncaughtException in worker will now log the error

packages/haste-task-karma/package.json, packages/haste-task-karma/test/index.spec.js
karma tests are failing (probably due to versions change).
The output now has green/red colors and it's better to ignore that for the sake of the tests.
=> add strip-ansi for karma output on tests

packages/haste-task-eslint/src/index.js, packages/haste-task-eslint/test/index.spec.js
Allow passing a custom formatter option
=> haste-task-eslint: support formatter

packages/haste-core/test/fixtures/error-outside-async.js, packages/haste-core/test/haste.spec.js, packages/haste-worker-farm/src/worker-bin.js
If an async error has been thrown outside if the main function call the worker will not get a message.
=> catch async errors that have been thrown outside of the main function call

packages/haste-task-typescript/src/index.js, packages/haste-task-typescript/src/utils.js, packages/haste-task-typescript/test/index.spec.js
The watch mode completion message on TypeScript 2.9 has been changed, from "Compilation complete.  Watching for file changes." to "Found X error/s. Watching for file changes.", so I simply changed the regex to look for "Watching for file changes" (because it appears in all versions - 2.9 and below) and simplified the condition that resolves the promise.
In addition, in case there's an error (so "Found X errors" appears), I draw the whole completion line in red.
=> typescript-task: support typescript@2.9 watch mode

.eslintrc, packages/haste-task-sass/package.json, packages/haste-task-sass/src/index.js
This PR moves `node-sass` from dependencies and into `devDependencies`. Installing `node-sass` should be up to whoever uses this package.
=> haste-task-sass: remove 'node-sass' from dependencies

packages/haste-task-karma/README.md, packages/haste-task-karma/package.json, packages/haste-task-karma/src/index.js
Remove karma from the dependencies of `haste-task-karma`, so it would be the user's decision whether to install it or not.
=> haste-task-karma: remove karma from the dependencies
